device: cuda # cuda / cpu / mps (using `transformers` as backend)
weights:
  doclayout_yolo: Structure/doclayout_yolo_docstructbench_imgsz1280_2501.pt # or Structure/layout_zh.pt
  layoutreader: Relation
models_dir: model_weight
layout_config: 
  model: doclayout_yolo
  reader:
    name: layoutreader
chat_config:
  weight_path: model_weight/Recognition
  backend: vllm_api # lmdeploy / vllm / transformers / api / vllm_api
  batch_size: 10 # active when using `transformers` as backend
api_config:
  url: http://192.168.20.58:9801/v1
  model_name: MonkeyOCR
  api_key: sk-xxx
