device: cuda # cuda / cpu / mps (using `transformers` as backend)
models:
  layout_detection:
    name: doclayout_yolo
    weight: /home/eric/workspace/MonkeyOCR/model_weight/Structure/doclayout_yolo_docstructbench_imgsz1280_2501.pt
  relation:
    name: layoutlm_v3
    weight: /home/eric/workspace/MonkeyOCR/model_weight/Relation
  llm:
    name: Qwen2.5-VL-7B-Instruct
    loras:
      table_image_otsl: table_image_otsl  
    url: http://192.168.20.58:9800/v1
